sonar.projectKey=aptlogica_sereni-email-smtp_81bfe731-8d64-4b02-a58c-81c48abd4f9a

sonar.language=go
sonar.sources=cmd,pkg,internal
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=Dockerfile,**/*_test.go
 
