sonar.projectKey=aptlogica_sereni-email-smtp_81bfe731-8d64-4b02-a58c-81c48abd4f9a

# Exclude Go test files and test folders
sonar.exclusions=**/*_test.go,**/test/**,**/tests/**,**/mock/**,**/mocks/**,sdk/**
 