sonar.projectKey=aptlogica_sereni-email-smtp

sonar.language=go
sonar.sources=cmd,pkg,internal
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=Dockerfile,**/*_test.go
 
